### ISSUE TITLE
Color contrast rules not working

### ISSUE THREAD

**Issue by craigmcginley** [dequelabs/react-axe#17]
Can't get any color contrast errors to trigger. Works as expected in 2.1.6, seems to be broken in 2.1.7. Guessing it's related to [this commit](https://github.com/dequelabs/react-axe/commit/e5f51dc09761e5b88e62d763b00013ab16a11256).

**Comment by dylanb** [comment]
@craigmcginley do you have specific examples you could put into a Codepen? REason I ask is because, as you can see from this screen shot, I have it working in the example application included in this project using axe-core 2.3.0

![image](https://user-images.githubusercontent.com/79245/29288104-8d3ecaae-8105-11e7-9202-cc58bbd6a459.png)

**Comment by craigmcginley** [comment]
I'm using create-react-app. I just spun up a fresh create-react-app project to test this out and included react-axe for non-production environment as the example shows (but with no config object). Added an input element and changed the header h2 background to white (already has white text). React-axe logs error for the input not having a label, but no error for color contrast. I've highlighted the white text in the following screenshot just for demonstration.

![screen shot 2017-08-14 at 3 58 22 pm](https://user-images.githubusercontent.com/6530818/29289169-6ffb7984-8109-11e7-9368-3118ab819464.png)

Notable is that I just installed react-axe today and **it seems to be using axe-core 2.3.1**.
My local node version: 8.2.1
My local npm version: 5.3.0

I can upload the simple project to github if it helps, or let me know any other ways I can assist. Thank you for the prompt response!

**Comment by dylanb** [comment]
@craigmcginley if you could upload the code to github that would be super useful - thanks!!

**Comment by craigmcginley** [comment]
Here's the playground project: https://github.com/craigmcginley/react-axe-test

```
$ yarn install
$ yarn start
```

**Comment by dylanb** [comment]
ok, I know why this is happening...we moved color contrast issues where the background and foreground colors are the same to the "incomplete" category. The reason for this is because the only times we see this are because either:

1. This is intentionally done to hide text that is intended only for a screen reader, or
2. The color contrast algorithm is detecting the colors incorrectly

If you look at this in the aXe extension, you will see that these issues appear as "review items"

![image](https://user-images.githubusercontent.com/79245/29385096-838ba298-82a4-11e7-9edd-17d16c335f01.png)

**Comment by dylanb** [comment]
Do you think you'd like to see these review items in the console of react-axe?

**Comment by craigmcginley** [comment]
I see! I was aiming to test that the package was working as expected in my application and figured the 1:1 color ratio was easiest to test on the CSS side. Didn't think to try other combinations. Thank you for looking into this!

I would expect 1:1 ratio to display a warning of some sort, as it does in the extension. Not sure how many cases these types of "unsure" warnings are presented, but perhaps react-axe displays them by default but is configurable? In the extension you can save a resolution to that warning, which is great.

**Comment by craigmcginley** [comment]
Closing. Tracked in [issue 18](https://github.com/dequelabs/react-axe/issues/18)
