### ISSUE TITLE
How do I test this plugin?

### ISSUE THREAD

**Issue by trezy** [dequelabs/react-axe#23]
I'm trying do some work on some server-rendered code, but it doesn't work because the plugin is trying to [use the `document` object in the `logElement` method](https://github.com/dequelabs/react-axe/blob/bbdaa629332ae8beaaf769f227a915100e20d8bb/index.js#L52). I forked the repo to see if I can figure out how best to add support for server-rendered code, but without any tests I'm not sure how to validate my changes.

Should I just be running the example and hoping for the best?

**Comment by dylanb** [comment]
This will not work for server-rendered code

**Comment by marcysutton** [comment]
@trezy aXe needs a browser to run, that's why you're getting an error about the `document` object. It would be awesome to test server-rendered code, but you'll have to get it running in a browser for aXe to test it. Maybe some kind of a first-pass could run on the server-rendered code only? Not sure if that's possible, but that's what I'd look into.
